services:
  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install
    startCommand: cd frontend && npm run start
    branch: main
    plan: free
  - type: web
    name: backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn main:app --workers 4 --bind 0.0.0.0:$PORT
    branch: main
    plan: free
